plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.jetbrains.compose)
    application
}

kotlin {
    jvmToolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
        vendor.set(JvmVendorSpec.JETBRAINS)
    }
}

val localSkikoVersion = providers.environmentVariable("SKIKO_VERSION")
val generatedLocalCmpOut = layout.projectDirectory.dir("../cmp/out/compose-multiplatform-core").asFile
val defaultLocalCmpOut = if (generatedLocalCmpOut.isDirectory) {
    generatedLocalCmpOut.absolutePath
} else {
    layout.projectDirectory.dir("../cmp").asFile.absolutePath
}
val localCmpOut = providers.gradleProperty("localCmpOut")
    .orElse(providers.environmentVariable("LOCAL_CMP_OUT"))
    .orElse(defaultLocalCmpOut)
val jbrSkiaJvmArgs = providers.gradleProperty("jbrSkiaInteropJvmArgs")
val jbrSkiaRenderMode = providers.gradleProperty("jbrSkiaRenderMode")
    .orElse(providers.environmentVariable("JBR_SKIA_RENDER_MODE"))
    .orElse("picture")
val forceTinyFullSceneOnceForTesting = providers.gradleProperty("skikoForceTinyFullSceneOnceForTesting")
    .orElse(providers.environmentVariable("SKIKO_FORCE_TINY_FULL_SCENE_ONCE_FOR_TEST"))
    .orElse("false")
val composeTextEnabled = providers.gradleProperty("magicJewelComposeText")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_TEXT"))
    .orElse("true")
val composeImageEnabled = providers.gradleProperty("magicJewelComposeImage")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_IMAGE"))
    .orElse("false")
val composeImageShaderEnabled = providers.gradleProperty("magicJewelComposeImageShader")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_IMAGE_SHADER"))
    .orElse("false")
val composeOpaqueShaderEnabled = providers.gradleProperty("magicJewelComposeOpaqueShader")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_OPAQUE_SHADER"))
    .orElse("false")
val composeCompositeOpaqueShaderEnabled = providers.gradleProperty("magicJewelComposeCompositeOpaqueShader")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_COMPOSITE_OPAQUE_SHADER"))
    .orElse("false")
val composeNoiseShaderEnabled = providers.gradleProperty("magicJewelComposeNoiseShader")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_NOISE_SHADER"))
    .orElse("false")
val composePictureShaderEnabled = providers.gradleProperty("magicJewelComposePictureShader")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_PICTURE_SHADER"))
    .orElse("false")
val composeTransformedShaderEnabled = providers.gradleProperty("magicJewelComposeTransformedShader")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_TRANSFORMED_SHADER"))
    .orElse("false")
val composeImageShaderColorFilterEnabled = providers.gradleProperty("magicJewelComposeImageShaderColorFilter")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_IMAGE_SHADER_COLOR_FILTER"))
    .orElse("false")
val composeCompositeShaderEnabled = providers.gradleProperty("magicJewelComposeCompositeShader")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_COMPOSITE_SHADER"))
    .orElse("false")
val composeCompositeShaderColorFilterEnabled = providers.gradleProperty("magicJewelComposeCompositeShaderColorFilter")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_COMPOSITE_SHADER_COLOR_FILTER"))
    .orElse("false")
val composeRuntimeEffectShaderEnabled = providers.gradleProperty("magicJewelComposeRuntimeEffectShader")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_RUNTIME_EFFECT_SHADER"))
    .orElse("false")
val composeRuntimeEffectShaderColorFilterEnabled = providers.gradleProperty("magicJewelComposeRuntimeEffectShaderColorFilter")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_RUNTIME_EFFECT_SHADER_COLOR_FILTER"))
    .orElse("false")
val composeLinearGradientShaderColorFilterEnabled = providers.gradleProperty("magicJewelComposeLinearGradientShaderColorFilter")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_LINEAR_GRADIENT_SHADER_COLOR_FILTER"))
    .orElse("false")
val composeRuntimeEffectPureColorEnabled = providers.gradleProperty("magicJewelComposeRuntimeEffectPureColor")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_RUNTIME_EFFECT_PURE_COLOR"))
    .orElse("false")
val composeRuntimeEffectUniformOnlyEnabled = providers.gradleProperty("magicJewelComposeRuntimeEffectUniformOnly")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_RUNTIME_EFFECT_UNIFORM_ONLY"))
    .orElse("false")
val composeRuntimeEffectChildOnlyEnabled = providers.gradleProperty("magicJewelComposeRuntimeEffectChildOnly")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_RUNTIME_EFFECT_CHILD_ONLY"))
    .orElse("false")
val composeRuntimeEffectBadChildEnabled = providers.gradleProperty("magicJewelComposeRuntimeEffectBadChild")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_RUNTIME_EFFECT_BAD_CHILD"))
    .orElse("false")
val composeRuntimeEffectColorFilterEnabled = providers.gradleProperty("magicJewelComposeRuntimeEffectColorFilter")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_RUNTIME_EFFECT_COLOR_FILTER"))
    .orElse("false")
val composeRuntimeEffectColorFilterChildEnabled = providers.gradleProperty("magicJewelComposeRuntimeEffectColorFilterChild")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_RUNTIME_EFFECT_COLOR_FILTER_CHILD"))
    .orElse("false")
val composeImageFilterEnabled = providers.gradleProperty("magicJewelComposeImageFilter")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_IMAGE_FILTER"))
    .orElse("false")
val composeImageColorMatrixFilterEnabled = providers.gradleProperty("magicJewelComposeImageColorMatrixFilter")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_IMAGE_COLOR_MATRIX_FILTER"))
    .orElse("false")
val composeColorFilterEnabled = providers.gradleProperty("magicJewelComposeColorFilter")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_COLOR_FILTER"))
    .orElse("false")
val composeColorMatrixFilterEnabled = providers.gradleProperty("magicJewelComposeColorMatrixFilter")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_COLOR_MATRIX_FILTER"))
    .orElse("false")
val composeLightingFilterEnabled = providers.gradleProperty("magicJewelComposeLightingFilter")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_LIGHTING_FILTER"))
    .orElse("false")
val composeDescriptorEvictionEnabled = providers.gradleProperty("magicJewelComposeDescriptorEviction")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_DESCRIPTOR_EVICTION"))
    .orElse("false")
val composePathEffectEnabled = providers.gradleProperty("magicJewelComposePathEffect")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_PATH_EFFECT"))
    .orElse("false")
val composeBlendModeEnabled = providers.gradleProperty("magicJewelComposeBlendMode")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_BLEND_MODE"))
    .orElse("false")
val composeGraphicsLayerEnabled = providers.gradleProperty("magicJewelComposeGraphicsLayer")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_GRAPHICS_LAYER"))
    .orElse("false")
val composeGraphicsLayerClipEnabled = providers.gradleProperty("magicJewelComposeGraphicsLayerClip")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_GRAPHICS_LAYER_CLIP"))
    .orElse("false")
val composeGraphicsLayerRoundClipEnabled = providers.gradleProperty("magicJewelComposeGraphicsLayerRoundClip")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_GRAPHICS_LAYER_ROUND_CLIP"))
    .orElse("false")
val composeGraphicsLayerPathClipEnabled = providers.gradleProperty("magicJewelComposeGraphicsLayerPathClip")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_GRAPHICS_LAYER_PATH_CLIP"))
    .orElse("false")
val composeGraphicsLayerBlendModeEnabled = providers.gradleProperty("magicJewelComposeGraphicsLayerBlendMode")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_GRAPHICS_LAYER_BLEND_MODE"))
    .orElse("false")
val composeGraphicsLayerColorFilterEnabled = providers.gradleProperty("magicJewelComposeGraphicsLayerColorFilter")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_GRAPHICS_LAYER_COLOR_FILTER"))
    .orElse("false")
val composeGraphicsLayerColorMatrixFilterEnabled = providers.gradleProperty("magicJewelComposeGraphicsLayerColorMatrixFilter")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_GRAPHICS_LAYER_COLOR_MATRIX_FILTER"))
    .orElse("false")
val composeGraphicsLayerRenderEffectEnabled = providers.gradleProperty("magicJewelComposeGraphicsLayerRenderEffect")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_GRAPHICS_LAYER_RENDER_EFFECT"))
    .orElse("false")
val composeGraphicsLayerRawImageFilterEffectEnabled =
    providers.gradleProperty("magicJewelComposeGraphicsLayerRawImageFilterEffect")
        .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_GRAPHICS_LAYER_RAW_IMAGE_FILTER_EFFECT"))
        .orElse("false")
val composeGraphicsLayerOffsetEffectEnabled = providers.gradleProperty("magicJewelComposeGraphicsLayerOffsetEffect")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_GRAPHICS_LAYER_OFFSET_EFFECT"))
    .orElse("false")
val composeGraphicsLayerChainedRenderEffectEnabled = providers.gradleProperty("magicJewelComposeGraphicsLayerChainedRenderEffect")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_GRAPHICS_LAYER_CHAINED_RENDER_EFFECT"))
    .orElse("false")
val composeGraphicsLayerShadowEnabled = providers.gradleProperty("magicJewelComposeGraphicsLayerShadow")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_GRAPHICS_LAYER_SHADOW"))
    .orElse("false")
val composeGraphicsLayerRotationXEnabled = providers.gradleProperty("magicJewelComposeGraphicsLayerRotationX")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_GRAPHICS_LAYER_ROTATION_X"))
    .orElse("false")
val composeGraphicsLayerRotationYEnabled = providers.gradleProperty("magicJewelComposeGraphicsLayerRotationY")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_GRAPHICS_LAYER_ROTATION_Y"))
    .orElse("false")
val composeGraphicsLayerNearCameraEnabled = providers.gradleProperty("magicJewelComposeGraphicsLayerNearCamera")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_GRAPHICS_LAYER_NEAR_CAMERA"))
    .orElse("false")
val composeGraphicsLayerOffCenterPivotEnabled = providers.gradleProperty("magicJewelComposeGraphicsLayerOffCenterPivot")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_GRAPHICS_LAYER_OFFCENTER_PIVOT"))
    .orElse("false")
val composeGraphicsLayerOffscreenEnabled = providers.gradleProperty("magicJewelComposeGraphicsLayerOffscreen")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_GRAPHICS_LAYER_OFFSCREEN"))
    .orElse("false")
val composeGraphicsLayerModulateAlphaEnabled = providers.gradleProperty("magicJewelComposeGraphicsLayerModulateAlpha")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_GRAPHICS_LAYER_MODULATE_ALPHA"))
    .orElse("false")
val composeTransformEnabled = providers.gradleProperty("magicJewelComposeTransform")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_TRANSFORM"))
    .orElse("false")
val composeConcatTransformEnabled = providers.gradleProperty("magicJewelComposeConcatTransform")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_CONCAT_TRANSFORM"))
    .orElse("false")
val composeSaveLayerEnabled = providers.gradleProperty("magicJewelComposeSaveLayer")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_SAVELAYER"))
    .orElse("false")
val composeSaveLayerFilterEnabled = providers.gradleProperty("magicJewelComposeSaveLayerFilter")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_SAVELAYER_FILTER"))
    .orElse("false")
val composeClipEnabled = providers.gradleProperty("magicJewelComposeClip")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_CLIP"))
    .orElse("false")
val composeClipOutEnabled = providers.gradleProperty("magicJewelComposeClipOut")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_CLIP_OUT"))
    .orElse("false")
val composeClipPathEnabled = providers.gradleProperty("magicJewelComposeClipPath")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_CLIP_PATH"))
    .orElse("false")
val composeDrawPathEnabled = providers.gradleProperty("magicJewelComposeDrawPath")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_DRAW_PATH"))
    .orElse("false")
val composeDrawArcEnabled = providers.gradleProperty("magicJewelComposeDrawArc")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_DRAW_ARC"))
    .orElse("false")
val composeDrawRoundRectEnabled = providers.gradleProperty("magicJewelComposeDrawRoundRect")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_DRAW_ROUND_RECT"))
    .orElse("false")
val composePointLinesEnabled = providers.gradleProperty("magicJewelComposePointLines")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_POINT_LINES"))
    .orElse("false")
val composePointDotsEnabled = providers.gradleProperty("magicJewelComposePointDots")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_POINT_DOTS"))
    .orElse("false")
val composeLinearGradientEnabled = providers.gradleProperty("magicJewelComposeLinearGradient")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_LINEAR_GRADIENT"))
    .orElse("false")
val composeLinearGradientStrokeEnabled = providers.gradleProperty("magicJewelComposeLinearGradientStroke")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_LINEAR_GRADIENT_STROKE"))
    .orElse("false")
val composeLinearGradientRoundRectEnabled = providers.gradleProperty("magicJewelComposeLinearGradientRoundRect")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_LINEAR_GRADIENT_ROUND_RECT"))
    .orElse("false")
val composeLinearGradientPathEnabled = providers.gradleProperty("magicJewelComposeLinearGradientPath")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_LINEAR_GRADIENT_PATH"))
    .orElse("false")
val composeRadialGradientEnabled = providers.gradleProperty("magicJewelComposeRadialGradient")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_RADIAL_GRADIENT"))
    .orElse("false")
val composeRadialGradientRoundRectEnabled = providers.gradleProperty("magicJewelComposeRadialGradientRoundRect")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_RADIAL_GRADIENT_ROUND_RECT"))
    .orElse("false")
val composeRadialGradientPathEnabled = providers.gradleProperty("magicJewelComposeRadialGradientPath")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_RADIAL_GRADIENT_PATH"))
    .orElse("false")
val composeSweepGradientEnabled = providers.gradleProperty("magicJewelComposeSweepGradient")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_SWEEP_GRADIENT"))
    .orElse("false")
val composeSweepGradientRoundRectEnabled = providers.gradleProperty("magicJewelComposeSweepGradientRoundRect")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_SWEEP_GRADIENT_ROUND_RECT"))
    .orElse("false")
val composeSweepGradientPathEnabled = providers.gradleProperty("magicJewelComposeSweepGradientPath")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_COMPOSE_SWEEP_GRADIENT_PATH"))
    .orElse("false")
val unsupportedTextEnabled = providers.gradleProperty("magicJewelUnsupportedText")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_UNSUPPORTED_TEXT"))
    .orElse("false")
val paragraphLayoutTextEnabled = providers.gradleProperty("magicJewelParagraphLayoutText")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_PARAGRAPH_LAYOUT_TEXT"))
    .orElse("false")
val imageCacheChurnEnabled = providers.gradleProperty("magicJewelImageCacheChurn")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_IMAGE_CACHE_CHURN"))
    .orElse("false")
val stableImageCacheChurnEnabled = providers.gradleProperty("magicJewelStableImageCacheChurn")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_STABLE_IMAGE_CACHE_CHURN"))
    .orElse("false")
val invalidSweepGradientEnabled = providers.gradleProperty("magicJewelInvalidSweepGradient")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_INVALID_SWEEP_GRADIENT"))
    .orElse("false")
val autoResizeEnabled = providers.gradleProperty("magicJewelAutoResize")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_AUTO_RESIZE"))
    .orElse("false")
val popupStressEnabled = providers.gradleProperty("magicJewelPopupStress")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_POPUP_STRESS"))
    .orElse("false")
val popupWindowStressEnabled = providers.gradleProperty("magicJewelPopupWindowStress")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_POPUP_WINDOW_STRESS"))
    .orElse("false")
val menuStressEnabled = providers.gradleProperty("magicJewelMenuStress")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_MENU_STRESS"))
    .orElse("false")
val fixedAnimationPhase = providers.gradleProperty("magicJewelFixedAnimationPhase")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_FIXED_ANIMATION_PHASE"))
val fixedFrameTicks = providers.gradleProperty("magicJewelFixedFrameTicks")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_FIXED_FRAME_TICKS"))
val pauseSwingAnimation = providers.gradleProperty("magicJewelPauseSwingAnimation")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_PAUSE_SWING_ANIMATION"))
    .orElse("false")
val swingIslandEnabled = providers.gradleProperty("magicJewelSwingIsland")
    .orElse(providers.environmentVariable("MAGIC_JEWEL_SWING_ISLAND"))
    .orElse("true")

configurations.configureEach {
    resolutionStrategy.eachDependency {
        if (requested.group == "androidx.compose.runtime") {
            useVersion("1.11.0-beta02")
            because("Match the Compose runtime API expected by the patched CMP UI jars")
        }
        localSkikoVersion.orNull?.takeIf { it.isNotBlank() }?.let { version ->
            if (requested.group == "org.jetbrains.skiko") {
                useVersion(version)
                because("Exercise the locally patched Skiko/JBR interop runtime")
            }
        }
    }
}

dependencies {
    implementation(patchedComposeRuntimeJars())
    implementation(compose.desktop.currentOs) {
        exclude(group = "org.jetbrains.compose.material")
    }
    implementation(libs.jewel.int.ui.standalone)
    implementation(libs.jewel.int.ui.decorated.window)
    implementation(libs.kotlinx.coroutines.swing)
}

application {
    mainClass.set("com.magicjewel.MainKt")
}

fun Project.patchedComposeRuntimeJars(): FileCollection {
    val root = file(localCmpOut.get())
    if (!root.isDirectory) return files()
    return files(
        fileTree(root) {
            include("annotation/annotation/build/libs/annotation-jvm-9999.0.0-SNAPSHOT.jar")
            include("collection/collection/build/libs/collection-jvm-9999.0.0-SNAPSHOT.jar")
            include("compose/**/build/libs/*-desktop-9999.0.0-SNAPSHOT.jar")
            include("compose/desktop/desktop/build/libs/desktop-jvm-9999.0.0-SNAPSHOT.jar")
        }
    )
}

fun JavaExec.configureMagicJewelJvm(interoperable: Boolean) {
    systemProperty("compose.swing.render.on.graphics", "true")
    systemProperty("apple.awt.application.name", "Magic Jewel")
    systemProperty("magic.jewel.compose.text", composeTextEnabled.get())
    systemProperty("magic.jewel.compose.image", composeImageEnabled.get())
    systemProperty("magic.jewel.compose.imageShader", composeImageShaderEnabled.get())
    systemProperty("magic.jewel.compose.opaqueShader", composeOpaqueShaderEnabled.get())
    systemProperty("magic.jewel.compose.compositeOpaqueShader", composeCompositeOpaqueShaderEnabled.get())
    systemProperty("magic.jewel.compose.noiseShader", composeNoiseShaderEnabled.get())
    systemProperty("magic.jewel.compose.pictureShader", composePictureShaderEnabled.get())
    systemProperty("magic.jewel.compose.transformedShader", composeTransformedShaderEnabled.get())
    systemProperty("magic.jewel.compose.imageShaderColorFilter", composeImageShaderColorFilterEnabled.get())
    systemProperty("magic.jewel.compose.compositeShader", composeCompositeShaderEnabled.get())
    systemProperty("magic.jewel.compose.compositeShaderColorFilter", composeCompositeShaderColorFilterEnabled.get())
    systemProperty("magic.jewel.compose.runtimeEffectShader", composeRuntimeEffectShaderEnabled.get())
    systemProperty("magic.jewel.compose.runtimeEffectShaderColorFilter", composeRuntimeEffectShaderColorFilterEnabled.get())
    systemProperty("magic.jewel.compose.linearGradientShaderColorFilter", composeLinearGradientShaderColorFilterEnabled.get())
    systemProperty("magic.jewel.compose.runtimeEffectPureColor", composeRuntimeEffectPureColorEnabled.get())
    systemProperty("magic.jewel.compose.runtimeEffectUniformOnly", composeRuntimeEffectUniformOnlyEnabled.get())
    systemProperty("magic.jewel.compose.runtimeEffectChildOnly", composeRuntimeEffectChildOnlyEnabled.get())
    systemProperty("magic.jewel.compose.runtimeEffectBadChild", composeRuntimeEffectBadChildEnabled.get())
    systemProperty("magic.jewel.compose.runtimeEffectColorFilter", composeRuntimeEffectColorFilterEnabled.get())
    systemProperty("magic.jewel.compose.runtimeEffectColorFilterChild", composeRuntimeEffectColorFilterChildEnabled.get())
    systemProperty("magic.jewel.compose.imageFilter", composeImageFilterEnabled.get())
    systemProperty("magic.jewel.compose.imageColorMatrixFilter", composeImageColorMatrixFilterEnabled.get())
    systemProperty("magic.jewel.compose.colorFilter", composeColorFilterEnabled.get())
    systemProperty("magic.jewel.compose.colorMatrixFilter", composeColorMatrixFilterEnabled.get())
    systemProperty("magic.jewel.compose.lightingFilter", composeLightingFilterEnabled.get())
    systemProperty("magic.jewel.compose.descriptorEviction", composeDescriptorEvictionEnabled.get())
    systemProperty("magic.jewel.compose.pathEffect", composePathEffectEnabled.get())
    systemProperty("magic.jewel.compose.blendMode", composeBlendModeEnabled.get())
    systemProperty("magic.jewel.compose.graphicsLayer", composeGraphicsLayerEnabled.get())
    systemProperty("magic.jewel.compose.graphicsLayerClip", composeGraphicsLayerClipEnabled.get())
    systemProperty("magic.jewel.compose.graphicsLayerRoundClip", composeGraphicsLayerRoundClipEnabled.get())
    systemProperty("magic.jewel.compose.graphicsLayerPathClip", composeGraphicsLayerPathClipEnabled.get())
    systemProperty("magic.jewel.compose.graphicsLayerBlendMode", composeGraphicsLayerBlendModeEnabled.get())
    systemProperty("magic.jewel.compose.graphicsLayerColorFilter", composeGraphicsLayerColorFilterEnabled.get())
    systemProperty("magic.jewel.compose.graphicsLayerColorMatrixFilter", composeGraphicsLayerColorMatrixFilterEnabled.get())
    systemProperty("magic.jewel.compose.graphicsLayerRenderEffect", composeGraphicsLayerRenderEffectEnabled.get())
    systemProperty(
        "magic.jewel.compose.graphicsLayerRawImageFilterEffect",
        composeGraphicsLayerRawImageFilterEffectEnabled.get(),
    )
    systemProperty("magic.jewel.compose.graphicsLayerOffsetEffect", composeGraphicsLayerOffsetEffectEnabled.get())
    systemProperty("magic.jewel.compose.graphicsLayerChainedRenderEffect", composeGraphicsLayerChainedRenderEffectEnabled.get())
    systemProperty("magic.jewel.compose.graphicsLayerShadow", composeGraphicsLayerShadowEnabled.get())
    systemProperty("magic.jewel.compose.graphicsLayerRotationX", composeGraphicsLayerRotationXEnabled.get())
    systemProperty("magic.jewel.compose.graphicsLayerRotationY", composeGraphicsLayerRotationYEnabled.get())
    systemProperty("magic.jewel.compose.graphicsLayerNearCamera", composeGraphicsLayerNearCameraEnabled.get())
    systemProperty("magic.jewel.compose.graphicsLayerOffCenterPivot", composeGraphicsLayerOffCenterPivotEnabled.get())
    systemProperty("magic.jewel.compose.graphicsLayerOffscreen", composeGraphicsLayerOffscreenEnabled.get())
    systemProperty("magic.jewel.compose.graphicsLayerModulateAlpha", composeGraphicsLayerModulateAlphaEnabled.get())
    systemProperty("magic.jewel.compose.transform", composeTransformEnabled.get())
    systemProperty("magic.jewel.compose.concatTransform", composeConcatTransformEnabled.get())
    systemProperty("magic.jewel.compose.saveLayer", composeSaveLayerEnabled.get())
    systemProperty("magic.jewel.compose.saveLayerFilter", composeSaveLayerFilterEnabled.get())
    systemProperty("magic.jewel.compose.clip", composeClipEnabled.get())
    systemProperty("magic.jewel.compose.clipOut", composeClipOutEnabled.get())
    systemProperty("magic.jewel.compose.clipPath", composeClipPathEnabled.get())
    systemProperty("magic.jewel.compose.drawPath", composeDrawPathEnabled.get())
    systemProperty("magic.jewel.compose.drawArc", composeDrawArcEnabled.get())
    systemProperty("magic.jewel.compose.drawRoundRect", composeDrawRoundRectEnabled.get())
    systemProperty("magic.jewel.compose.pointLines", composePointLinesEnabled.get())
    systemProperty("magic.jewel.compose.pointDots", composePointDotsEnabled.get())
    systemProperty("magic.jewel.compose.linearGradient", composeLinearGradientEnabled.get())
    systemProperty("magic.jewel.compose.linearGradientStroke", composeLinearGradientStrokeEnabled.get())
    systemProperty("magic.jewel.compose.linearGradientRoundRect", composeLinearGradientRoundRectEnabled.get())
    systemProperty("magic.jewel.compose.linearGradientPath", composeLinearGradientPathEnabled.get())
    systemProperty("magic.jewel.compose.radialGradient", composeRadialGradientEnabled.get())
    systemProperty("magic.jewel.compose.radialGradientRoundRect", composeRadialGradientRoundRectEnabled.get())
    systemProperty("magic.jewel.compose.radialGradientPath", composeRadialGradientPathEnabled.get())
    systemProperty("magic.jewel.compose.sweepGradient", composeSweepGradientEnabled.get())
    systemProperty("magic.jewel.compose.sweepGradientRoundRect", composeSweepGradientRoundRectEnabled.get())
    systemProperty("magic.jewel.compose.sweepGradientPath", composeSweepGradientPathEnabled.get())
    systemProperty("magic.jewel.unsupportedText", unsupportedTextEnabled.get())
    systemProperty("magic.jewel.paragraphLayoutText", paragraphLayoutTextEnabled.get())
    systemProperty("magic.jewel.imageCacheChurn", imageCacheChurnEnabled.get())
    systemProperty("magic.jewel.stableImageCacheChurn", stableImageCacheChurnEnabled.get())
    systemProperty("magic.jewel.invalidSweepGradient", invalidSweepGradientEnabled.get())
    systemProperty("magic.jewel.autoResize", autoResizeEnabled.get())
    systemProperty("magic.jewel.popupStress", popupStressEnabled.get())
    systemProperty("magic.jewel.popupWindowStress", popupWindowStressEnabled.get())
    systemProperty("magic.jewel.menuStress", menuStressEnabled.get())
    fixedAnimationPhase.orNull?.let { systemProperty("magic.jewel.fixedAnimationPhase", it) }
    fixedFrameTicks.orNull?.let { systemProperty("magic.jewel.fixedFrameTicks", it) }
    systemProperty("magic.jewel.pauseSwingAnimation", pauseSwingAnimation.get())
    systemProperty("magic.jewel.swingIsland", swingIslandEnabled.get())
    if (interoperable) {
        systemProperty("compose.swing.render.on.jbr.skia", "true")
        systemProperty("skiko.jbr.interop.debugOverlay", "true")
        systemProperty("skiko.jbr.interop.forceTinyFullSceneOnceForTesting", forceTinyFullSceneOnceForTesting.get())
        when (jbrSkiaRenderMode.get()) {
            "commands" -> systemProperty("skiko.jbr.interop.renderCommands", "true")
            "diagnostic" -> systemProperty("skiko.jbr.interop.renderDiagnostic", "true")
            else -> systemProperty("skiko.jbr.interop.renderPicture", "true")
        }
    }
    jbrSkiaJvmArgs.orNull
        ?.split(Regex("\\s+"))
        ?.filter { it.isNotBlank() }
        ?.let(::jvmArgs)
}

tasks.named<JavaExec>("run") {
    val patchedCompose = patchedComposeRuntimeJars()
    classpath = patchedCompose + sourceSets.main.get().runtimeClasspath
    configureMagicJewelJvm(interoperable = false)
    doFirst {
        logger.lifecycle("Prepending ${patchedCompose.files.size} patched CMP jars from ${localCmpOut.get()}")
    }
}

tasks.register<JavaExec>("runJbrSkiaInterop") {
    group = ApplicationPlugin.APPLICATION_GROUP
    description = "Run Magic Jewel through SwingGraphics with the JBR Skia interop fast path enabled."
    val patchedCompose = patchedComposeRuntimeJars()
    classpath = patchedCompose + sourceSets.main.get().runtimeClasspath
    mainClass.set("com.magicjewel.MainKt")
    configureMagicJewelJvm(interoperable = true)
    doFirst {
        logger.lifecycle("Prepending ${patchedCompose.files.size} patched CMP jars from ${localCmpOut.get()}")
    }
}
